name: Pylint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pylint==2.2.2
        git submodule update --init --recursive
        if [ -f aws_iot/requirements.txt ]; then pip install -r aws_iot/requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        python3 -m pylint aws_iot/
